version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    volumes:
        - ./data/mysql/:/var/lib/mysql
    environment:
        - MARIADB_ROOT_PASSWORD=MYROOTPASSWORD
        - MARIADB_DATABASE=piwigo
        - MARIADB_USER=piwigo
        - MARIADB_PASSWORD=MYUSERPASSWORD
  piwigo:
    build: .
    environment:
        - BASH_MODE=set -e
    depends_on:
        - mariadb
    volumes:
        - ./data/piwigo/data/galleries:/var/www/galleries
        - ./data/piwigo/data/local:/var/www/local
        - ./data/piwigo/data/plugins:/var/www/plugins
        - ./data/piwigo/data/themes:/var/www/themes
        - ./data/piwigo/cache:/var/www/_data/i
        - ./data/piwigo/upload:/var/www/upload
        - ./data/var/log:/var/log
        - ./data/var/log/piwigo:/var/log/nginx
    ports:
        - "9999:80"
    hostname: piwigo
    domainname: MYDOMAIN.COM
