name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Enter Tag to create"
        required: true
        default: "latest"
  push:
    #branches: '*'
    tags: '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{vars.DOCKERUSER}}/piwigo
          tags: |
            # set latest tag for main branch
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=semver,pattern={{major}}.{{minor}}*
#            type=ref,event=branch
#            type=ref,event=pr
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check on tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["${{ vars.DOCKERUSERE }}/piwigo:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='${{ vars.DOCKERUSER }}/piwigo:${{inputs.tags}}'
          fi
          echo '${TAGS}'
          echo 'tags=${TAGS}' >> GITHUB_OUTPUT
      - name: Echo tags
        run: |
          echo -e "tags: \n ${{steps.gen_tags.outputs.tags}}"
          echo -e "meta-tags: ${{steps.meta.outputs.tags}}"
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKERUSER }}/piwigo:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
      - name: Docker Hub Description
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERUSER }}/piwigo
