name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Enter Tag to create"
        required: true
        default: "latest"
  push:
#    branches: '*'
#    tags: '*'

jobs:
  tagandci:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate tags
        id: find_tags
        run: |
          N_TAG=$(grep 'FROM php:' Dockerfile|sed 's/FROM php://g')
          M_TAG=$(grep 'ARG PIWIGO_VERSION' Dockerfile|sed 's/ARG PIWIGO_VERSION=//g'|sed 's/"//g')
          New_TAG=$M_TAG-php$N_TAG
          echo "New Tag generated: $New_TAG, $M_TAG"
          echo "NEW_TAG=$New_TAG" >> GITHUB_OUTPUT
          echo "M_TAG=$M_TAG" >> GITHUB_OUTPUT
          echo "tags=$M_TAG, $New_TAG" >> GITHUB_OUTPUT
      - name: Auto-tag repo with full tag
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_SEC_TOKEN }}
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $M_TAG
          git push origin tag $M_TAG
          git tag $NEW_TAG
          git push origin tag $NEW_TAG
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{vars.DOCKERUSER}}/piwigo
          tags: |
            # set latest tag for main branch
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=semver,pattern={{major}}.{{minor}}*
      - name: Check on tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["${{ vars.DOCKERUSERE }}/piwigo:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='${{ vars.DOCKERUSER }}/piwigo:${{inputs.tags}}'
          fi
          echo '${TAGS}'
          echo 'tags=${TAGS}' >> GITHUB_OUTPUT
      - name: Echo tags
        id: echo_tags
        run: |
          echo -e "tags: \n ${{steps.gen_tags.outputs.tags}}"
          echo -e "meta-tags: ${{steps.meta.outputs.tags}}"
          echo -e "gen-tags: ${{steps.find_tags.outputs.tags}}"
          echo -e "debug=true" >> GITHUB_OUTPUT
      - name: Stop if debug
        if: ${{ steps.echo_tags.outputs.debug }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Debugging, so stop here')

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKERUSER }}/piwigo:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
      - name: Docker Hub Description
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERUSER }}/piwigo
